=== 2425-Temporada2-1DW3/Temporada2_Grupo1_LM/paginaWeb+xml(Unai)/xml/clasificacion.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema"
           targetNamespace="http://www.example.com/clasificacion"
           xmlns="http://www.example.com/clasificacion"
           elementFormDefault="qualified">

    <xs:element name="tabla">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="fila" maxOccurs="unbounded">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="posicion" type="xs:int"/>
                            <xs:element name="equipo" type="xs:string"/>
                            <xs:element name="puntos" type="xs:int"/>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
            </xs:sequence>
        </xs:complexType>
    </xs:element>

</xs:schema>

=== 2425-Temporada2-1DW3/Temporada2_Grupo1_LM/paginaWeb+xml(Unai)/xml/clasificacion3.xml
<?xml version="1.0" encoding="UTF-8"?>
<?xml-stylesheet type="text/xsl" href="clasificacion.xslt"?>
<tabla xmlns="http://www.example.com/clasificacion"
       xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
       xsi:schemaLocation="http://www.example.com/clasificacion clasificacion.xsd">
    <fila>
        <posicion>1</posicion>
        <equipo> A</equipo>
        <puntos>10</puntos>
    </fila>
    <fila>
        <posicion>2</posicion>
        <equipo> B</equipo>
        <puntos>8</puntos>
    </fila>
    <fila>
        <posicion>3</posicion>
        <equipo> C</equipo>
        <puntos>6</puntos>
    </fila>
</tabla>

=== 2425-Temporada2-1DW3/Temporada2_Grupo1_LM/paginaWeb + xml/xml/clasificacion4.xml
<?xml version="1.0" encoding="UTF-8"?>
<?xml-stylesheet type="text/xsl" href="clasificacion.xslt"?>
<tabla xmlns="http://www.example.com/clasificacion"
       xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
       xsi:schemaLocation="http://www.example.com/clasificacion clasificacion.xsd">
    <fila>
        <posicion>3</posicion>
        <equipo>Equipo A</equipo>
        <puntos>7</puntos>
    </fila>
    <fila>
        <posicion>1</posicion>
        <equipo>Equipo B</equipo>
        <puntos>55</puntos>
    </fila>
    <fila>
        <posicion>2</posicion>
        <equipo>Equipo C</equipo>
        <puntos>20</puntos>
    </fila>
</tabla>
